spring.application.name=lim-onApi
server.servlet.context-path=/api-limon/v1

logging.level.root=INFO
spring.application.timezone=UTC

#------ Servlet Session Security ------
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.name=JSESSIONID
server.forward-headers-strategy=native
#server.ssl.enabled=false
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=3MB

#------ Spring Mail Configuration ------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lim.on.events.peru@gmail.com
spring.mail.password=APP_PASSWORD_GENERADO
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#------ Security JWT ------
security.jwt.secret=cambia-esto-por-una-clave-larga-32+chars
security.jwt.access-ttl=PT12H
security.jwt.refresh-ttl=PT12H
security.jwt.refresh-ttl-remember=PT12H
security.jwt.refresh-cookie-name=rt
security.jwt.refresh-cookie-secure=true
security.jwt.refresh-cookie-samesite=Lax
security.jwt.refresh-cookie-domain=lim-on.social

#------ Google OAuth ------
google.issuer=https://accounts.google.com
google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs

#------ Application properties ------
application.transaction.days-show=30

#------ Default Profile ------
spring.profiles.active=dev
