spring.datasource.url=jdbc:mysql://localhost:3306/limondbv2
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#--------------- Doc Config ---------------
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.model-converters.enabled=true

#----------- Logging Levels -----------
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.com.pe.limon.api.service=DEBUG
logging.level.com.pe.limon.api.repository=DEBUG
logging.level.com.pe.limon.api.gateway=DEBUG
logging.level.com.pe.limon.api.core=DEBUG
logging.level.com.pe.limon.api.transactions=DEBUG
logging.level.com.pe.limon.api.core.security=DEBUG

#------ Servlet Session Security ------
server.servlet.session.cookie.secure=false

#------ Files Configuration ------
application.images.allowed-mime-types=image/jpeg,image/png,image/gif
application.images.max-file-size=5242880
application.images.dangerous-extensions=exe,sh,bat,cmd,js,vbs
application.images.invalidate-patterns=[^a-zA-Z0-9\\-_.]
application.images.url.image-qr=http://localhost:8080/api-limon/v1/client/access/passes/image/
application.images.url.image-user=http://localhost:8080/api-limon/v1/public/users/profile/image/
application.images.url.image-event=http://localhost:8080/api-limon/v1/public/events/image/
application.images.directory.qr=C:/Users/U19201672/Documents/Proyectos/limonv2/lim-onApi/src/main/resources/images/qr
application.images.directory.voucher=C:/Users/U19201672/Documents/Proyectos/limonv2/lim-onApi/src/main/resources/images/voucher
application.images.directory.event=C:/Users/U19201672/Documents/Proyectos/limonv2/lim-onApi/src/main/resources/images/event
application.images.directory.user=C:/Users/U19201672/Documents/Proyectos/limonv2/lim-onApi/src/main/resources/images/user

#------ OAuth2 Security Configuration ------
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=

#------ Security JWT ------
security.jwt.secret=cambia-esto-por-una-clave-larga-32+chars
security.jwt.access-ttl=PT24H
security.jwt.refresh-ttl=PT24H
security.jwt.refresh-ttl-remember=PT24H
security.jwt.refresh-cookie-name=rt
security.jwt.refresh-cookie-secure=false
security.jwt.refresh-cookie-samesite=Lax
security.jwt.refresh-cookie-domain=
security.signature.secret.key = limon_qr_secret_2025

#------ Cache Configuration ------
application.cache.maximum-size=100000
application.cache.expires-after-write=60

# ----- Mercado Pago (API) -----
payment.mercado-pago.access-token=TEST-5477514732412763-080521-3289bb025a1e7528b559eb62e7dd45fc-2581814574
payment.mercado-pago.public-key=TEST-e31243ee-93d0-4890-ad5c-25f26dc48038
payment.mercado-pago.webhook-key=
payment.mercado-pago.public-endpoint.platform-payments=https://api.mercadopago.com/platforms/pci/yape/v1/payment?public_key=${payment.mercado-pago.public-key}
payment.mercado-pago.public-endpoint.payments=https://api.mercadopago.com/v1/payments


# ----- SPRING MAIL (SMTP) -----
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=Lim-On <no-reply@lim-on.social>
app.mail.enable-async=true


#----- OTHERS CONFIGURATION ---------
application.front.url.complete-profile=http://localhost:4200/authentication/register
security.cors.allowed-origins=http://localhost:4200
spring.jackson.time-zone=America/Lima
